### ISSUE TITLE
Preise passen nicht.

### ISSUE THREAD

**Issue by detafun** [sirjojo69/ioBroker.awattar#1]
Also erst mal klasse für deine Umsetzung.

Mir ist Aufgefallen. Aktuell Beispiel gerade Abgerufen:
1 Awarrar Preis
![grafik](https://user-images.githubusercontent.com/44980055/97335128-c204b880-187d-11eb-8ae5-726ac6353441.png)

Hier steht aktuell der Preis von 3-4 Uhr Nachts Preis: 0,43 ct/kwh
Bei dir in der Liste:
![grafik](https://user-images.githubusercontent.com/44980055/97335445-26c01300-187e-11eb-925c-2b02b4578e11.png)

Auch Zeit 3-4 Uhr Nachts Preis 0,0043 ct/kwh Preis pro Kwh

Als erstes mal auf die Schnelle.

**Comment by Habedere** [comment]
Ja bei mir ebenso...

Wäre auch noch top wenn zuästzlich ein Datenfeld eingepflegt wird, welches den effektiven Strompreis anzeigt.
Also in meinem Fall z.B.
**20,19** + EPEX Spot DE + 0,250
Wobei der erste Wert je nach Netz variabel ist und somit im Adapter einstellbar sein muss.

**Comment by sirjojo69** [comment]
> 
> 
> Also erst mal klasse für deine Umsetzung.
> 
> Mir ist Aufgefallen. Aktuell Beispiel gerade Abgerufen:
> 1 Awarrar Preis
> ![grafik](https://user-images.githubusercontent.com/44980055/97335128-c204b880-187d-11eb-8ae5-726ac6353441.png)
> 
> Hier steht aktuell der Preis von 3-4 Uhr Nachts Preis: 0,43 ct/kwh
> Bei dir in der Liste:
> ![grafik](https://user-images.githubusercontent.com/44980055/97335445-26c01300-187e-11eb-925c-2b02b4578e11.png)
> 
> Auch Zeit 3-4 Uhr Nachts Preis 0,0043 ct/kwh Preis pro Kwh
> 
> Als erstes mal auf die Schnelle.

hi... vielen dank für deinen test und dein feedback. den umrechnungsbug habe ich gefixt. dabei ist mir aufgefallen dass über die schnittstelle netto preise kommen. Passt das oder sollte ich die aktuell gültige Mwst dazu rechnen (vielleicht einstellbar in einem setting des adapters) ?

**Comment by sirjojo69** [comment]
> 
> 
> Ja bei mir ebenso...
> 
> Wäre auch noch top wenn zuästzlich ein Datenfeld eingepflegt wird, welches den effektiven Strompreis anzeigt.
> Also in meinem Fall z.B.
> **20,19** + EPEX Spot DE + 0,250
> Wobei der erste Wert je nach Netz variabel ist und somit im Adapter einstellbar sein muss.

hi... hmmm.... wie wäre es mit:
-einem Adapter Setting "Arbeitspreis"  (dort trägt man dann "seinen" Preis ein für: "Netznutzung" + "Umlagen, Abgaben, Steuern" + "Kosten für Ökostromzertifikate, Abrechnung und Vertrieb" )
- dann würde ich bei den Preisen ein zusätzliches Feld machen "TotalPriceKwh" wo dann der Arbeitspreis aus den Settings und der ermittelte börsenpreis für die stunde addiert werden.

**Comment by Habedere** [comment]
> > Ja bei mir ebenso...
> > Wäre auch noch top wenn zuästzlich ein Datenfeld eingepflegt wird, welches den effektiven Strompreis anzeigt.
> > Also in meinem Fall z.B.
> > **20,19** + EPEX Spot DE + 0,250
> > Wobei der erste Wert je nach Netz variabel ist und somit im Adapter einstellbar sein muss.
> 
> hi... hmmm.... wie wäre es mit:
> -einem Adapter Setting "Arbeitspreis" (dort trägt man dann "seinen" Preis ein für: "Netznutzung" + "Umlagen, Abgaben, Steuern" + "Kosten für Ökostromzertifikate, Abrechnung und Vertrieb" )
> 
> * dann würde ich bei den Preisen ein zusätzliches Feld machen "TotalPriceKwh" wo dann der Arbeitspreis aus den Settings und der ermittelte börsenpreis für die stunde addiert werden.

Das wäre top!
Vielen dank für den Adapter - da warte ich schon länger drauf :)

**Comment by detafun** [comment]
Bitte für jedes Anliegen, wenn es nicht das selbe ist ein extra Thread hier anlegen, sonst wird es unübersichtlich.

**Comment by detafun** [comment]
> hi... vielen dank für deinen test und dein feedback. den umrechnungsbug habe ich gefixt. dabei ist mir aufgefallen dass über die schnittstelle netto preise kommen. Passt das oder sollte ich die aktuell gültige Mwst dazu rechnen (vielleicht einstellbar in einem setting des adapters) ?

Das mit dem Netto / Brutto ist egal.  Kannst ja ein Feld reinbringen Netto Preis , Brutto Preis. In Der Config aber Manuell den Steuersatz einfügbar machen.

**Comment by sirjojo69** [comment]
ich close das issue mal hier. alle hier besprochenen sachen sind in 1.0.4 umgesetzt. sollte was nicht richtig laufen bitte neues Issue aufmachen.
