### ISSUE TITLE
HourlyCap berechnung

### ISSUE THREAD

**Issue by hyperbit00** [sirjojo69/ioBroker.awattar#13]
In der Beschreibung wird geschrieben, dass die Tarife Hourly und Hourly Cap geladen werden. Aber im Feed werden doch nur die Börsenpreise übermittelt.

Wie können wir davon die Hourly CAP (syncbonus) Ableiten? Ist das Mit dem Adapter überhaupt mögich?

**Comment by sirjojo69** [comment]
genau... es werden die preise für houly und hourly cap geladen. die schnittstelle von awattar bietet die allgemein gültigen preise pro stunde an. alles was individuell ist muss selber ausgerechnet werden. der sync bonus ist ja von deinem verhalten abhängig, dass du mit diesem adapter beeinflussen kannst (grossverbraucher nur zu den günstigen stunden schalten)
