### ISSUE TITLE
Preis zum aktuellen Zeitpunkt

### ISSUE THREAD

**Issue by uddw** [sirjojo69/ioBroker.awattar#14]
Ich würde gerne die aktuellen Kosten als Zeitreihe aufnehmen, um mit den Stromverbrauchsdaten von Discovergy meine aktuelle Geldverbrennungsrate auszurechnen.

Das wäre komfortabler möglich, wenn der Adapter selbst direkt ein Objekt anbieten würde, das stets die Kosten des *aktuellen* Zeitraums liefern würde - also mit einer Aktualisierung jeweils nach dem Ende des gerade vergangenen Zeitraums und nicht nur alle 24h.

**Comment by sirjojo69** [comment]
hmmm... dieser adapter soll (lediglich) die preisdaten liefern, damit man "was auch immer man damit machen möchte" umsetzen kann. ich würd vorschlagen du machst dir einen eigenen datenpunkt und dann ein zeitplan gesteuertes script dass genau das macht. es gibt einfach zu viele use cases die man sich in der umsetzung vorstellen könnte, als dass man sie alle in diesen adapter packen könnte....
