### ISSUE TITLE
Nächster Tag wird nicht abgeholt

### ISSUE THREAD

**Issue by noriyuki41** [sirjojo69/ioBroker.awattar#19]
Hallo,

Seit dem letzten Update kommt es öfters vor dass der nächste Tag nicht abgeholt wird sondern nur mit dem aktuellen überschreiben wird.
Beispielsweise hat dann awattar.0.prices.0.startDate den Wert 23.04.2022 und awattar.0.prices.30.startDate abenfalls das gleiche Datum.
Einen Updatezyklus später (24h) ist es dann meist wieder korrekt.
Die API von awattar liefert allerdings korrekte Werte. Auch ein neuerliches Abholen bringt keine Veränderung.
Siehe auch Screenshots.

G
Stefan
![Screenshot 2022-04-24 115439_LI](https://user-images.githubusercontent.com/40025978/164971158-6dac2c67-1053-4e5c-a497-b0b959803496.jpg)
![Screenshot 2022-04-24 120142](https://user-images.githubusercontent.com/40025978/164971162-44bc2f16-d0f8-49d3-967f-6474fc0e5d33.jpg)
n

**Comment by noriyuki41** [comment]
Neuer Fall: Seit 3 Tagen werden die Daten nicht mehr abgeholt.

![Screenshot 2022-11-05 143006](https://user-images.githubusercontent.com/40025978/200122382-0b438e4d-2ea4-46d6-af4f-7de278979be5.jpg)

**Comment by noriyuki41** [comment]
Wie und wo kann ich herausfinden warum die Instanz nicht mehr arbeitet?

**Comment by sirjojo69** [comment]
> Neuer Fall: Seit 3 Tagen werden die Daten nicht mehr abgeholt.
> 
> ![Screenshot 2022-11-05 143006](https://user-images.githubusercontent.com/40025978/200122382-0b438e4d-2ea4-46d6-af4f-7de278979be5.jpg)

Hi... bei mir läuft alles normal. In den letzten 7 tagen wurden die Werte ganz normal um 15 uhr aktualisiert. Hast du den Adapter schon mal restartet? (war jetzt bei mir noch nie nötig, aber wer weiss)

**Comment by noriyuki41** [comment]
Servus,

 

Adapter Restart hat alles nichts geholfen.

Erst der Neustart des gesamten iobroker hat es gebracht.

 

Muss mir überlegen wie ich das Problem in Zukunft detektiere weil an den Werten hängt meine gesamte Energieoptimierung vom Haus.

 

G
Stefan

 

 

Von: sirjojo69 ***@***.***> 
Gesendet: Montag, 7. November 2022 20:23
An: sirjojo69/ioBroker.awattar ***@***.***>
Cc: noriyuki41 ***@***.***>; Author ***@***.***>
Betreff: Re: [sirjojo69/ioBroker.awattar] Nächster Tag wird nicht abgeholt (Issue #19)

 

Neuer Fall: Seit 3 Tagen werden die Daten nicht mehr abgeholt.

 <https://user-images.githubusercontent.com/40025978/200122382-0b438e4d-2ea4-46d6-af4f-7de278979be5.jpg> 

Hi... bei mir läuft alles normal. In den letzten 7 tagen wurden die Werte ganz normal um 15 uhr aktualisiert. Hast du den Adapter schon mal restartet? (war jetzt bei mir noch nie nötig, aber wer weiss)
