### ISSUE TITLE
Start Stop Zeit Format

### ISSUE THREAD

**Issue by mucke1985** [sirjojo69/ioBroker.awattar#21]
Hallo SirJojo69

Danke erstmal für das tolle Programm .

Ich würde gerne die erzeugten Datenpunte wie Start und Stop Zeit nutzen um ein 15kWh Akku zu laden, das natürlich am besten zu den Zeiten an dem der Strom am „Billigsten „ ist.

Nun bin ich kein Programmierer und Arbeite deshalb sehr viel mit Blockly.
Währe es ev. möglich das du beim nächsten update die Zeitausgabe umgestaltest so das Start und Stop Zeit nicht  wie bisher in 02:00:00 AM oder 02:00:00 PM   angelegt werden.

Würde das Objekt das Format 02:00 oder  14:00  haben, würde man damit in Blockly wesentlich leichter arbeiten können, das würde vielen die Blockly und dein Programm  benutzen das Leben erleichtern.   
Das Programm funktionier übrigens auch super mit Awattar Österreich

**Comment by sirjojo69** [comment]
Hi, für diese Zwecke gibt es in den jeweiligen Stundenobjekten den Start oder Ende Timestamp. Denn kannst du dir in blockly umrechnen lassen und dann darauf steuern was immer du magst...
