### ISSUE TITLE
Timestamps - GMT vs ME(S)Z

### ISSUE THREAD

**Issue by vagabond235** [sirjojo69/ioBroker.awattar#22]
Ich habe seit gestern den Adapter laufen und bin heute auf eine Diskrepanz von einer Stunde zwischen "meiner" Visualisierung und der auf awattar.at publizierten gestoßen. Sind die in den iobroker objects eingetragenen timestamps in GMT oder ME(S)Z?

**Comment by sirjojo69** [comment]
die doku gibt es nicht her.
https://www.awattar.de/services/api
Wenn ich bei mir mit https://www.awattar.de/tariffs/hourly vergleiche passt es genau.
![Screenshot 2023-01-12 162036](https://user-images.githubusercontent.com/54443945/212106941-cd49805e-1e7f-41e8-901e-35a36f6dfac0.png)
