### ISSUE TITLE
possibility to use awattar adapter for other epex spot provider

### ISSUE THREAD

**Issue by Qlink84** [sirjojo69/ioBroker.awattar#28]
I've tried to use awattar adapter for my epex spot provider "SmartEnergy".

I've tried to just exchange API URL in adapter settings with the one provided here: https://www.smartenergy.at/api-schnittstellen

But as expected it is not as easy as that ;)
I get following warning in log:

`Read-only state "awattar.0.Rawdata" has been written without ack-flag with value "{"tariff":"EPEXSPOTAT","unit":"ct/kWh","interval":15,"data":[{"date":"2023-12-31T00:00:00+01:00","value":4.118},{"date":"2023-12-31T00:15:00+01:00","value":4.118},{"date":"2023-12-31T00:30:00+01:00","value":4.118},{"date":"2023-12-31T00:45:00+01:00","value":4.118},{"date":"2023-12-31T01:00:00+01:00","value":1.474},{"date":"2023-12-31T01:15:00+01:00","value":1.474},{"date":"2023-12-31T01:30:00+01:00","value":1.474},{"date":"2023-12-31T01:45:00+01:00","value":1.474},{"date":"2023-12-31T02:00:00+01:00","value":0.48},{"date":"2023-12-31T02:15:00+01:00","value":0.48},{"date":"2023-12-31T02:30:00+01:00","value":0.48},{"date":"2023-12-31T02:45:00+01:00","value":0.48},{"date":"2023-12-31T03:00:00+01:00","value":0.037},{"date":"2023-12-31T03:15:00+01:00","value":0.037},{"date":"2023-12-31T03:30:00+01:00","value":0.037},{"date":"2023-12-31T03:45:00+01:00","value":0.037},{"date":"2023-12-31T04:00:00+01:00","value":0.629},{"date":"2023-12-31T04:15:00+01:00","value":0.629},{"date":"2023-12-31T04:30:00+01:00","value":0.629},{"date":"2023-12-31T04:45:00+01:00","value":0.629},{"date":"2023-12-31T05:00:00+01:00","value":1.364},{"date":"2023-12-31T05:15:00+01:00","value":1.364},{"date":"2023-12-31T05:30:00+01:00","value":1.364},{"date":"2023-12-31T05:45:00+01:00","value":1.364},{"date":"2023-12-31T06:00:00+01:00","value":1.312},{"date":"2023-12-31T06:15:00+01:00","value":1.312},{"date":"2023-12-31T06:30:00+01:00","value":1.312},{"date":"2023-12-31T06:45:00+01:00","value":1.312},{"date":"2023-12-31T07:00:00+01:00","value":1.48},{"date":"2023-12-31T07:15:00+01:00","value":1.48},{"date":"2023-12-31T07:30:00+01:00","value":1.48},{"date":"2023-12-31T07:45:00+01:00","value":1.48},{"date":"2023-12-31T08:00:00+01:00","value":1.8},{"date":"2023-12-31T08:15:00+01:00","value":1.8},{"date":"2023-12-31T08:30:00+01:00","value":1.8},{"date":"2023-12-31T08:45:00+01:00","value":1.8},{"date":"2023-12-31T09:00:00+01:00","value":2.226},{"date":"2023-12-31T09:15:00+01:00","value":2.226},{"date":"2023-12-31T09:30:00+01:00","value":2.226},{"date":"2023-12-31T09:45:00+01:00","value":2.226},{"date":"2023-12-31T10:00:00+01:00","value":1.68},{"date":"2023-12-31T10:15:00+01:00","value":1.68},{"date":"2023-12-31T10:30:00+01:00","value":1.68},{"date":"2023-12-31T10:45:00+01:00","value":1.68},{"date":"2023-12-31T11:00:00+01:00","value":2.047},{"date":"2023-12-31T11:15:00+01:00","value":2.047},{"date":"2023-12-31T11:30:00+01:00","value":2.047},{"date":"2023-12-31T11:45:00+01:00","value":2.047},{"date":"2023-12-31T12:00:00+01:00","value":2.177},{"date":"2023-12-31T12:15:00+01:00","value":2.177},{"date":"2023-12-31T12:30:00+01:00","value":2.177},{"date":"2023-12-31T12:45:00+01:00","value":2.177},{"date":"2023-12-31T13:00:00+01:00","value":1.847},{"date":"2023-12-31T13:15:00+01:00","value":1.847},{"date":"2023-12-31T13:30:00+01:00","value":1.847},{"date":"2023-12-31T13:45:00+01:00","value":1.847},{"date":"2023-12-31T14:00:00+01:00","value":2.17},{"date":"2023-12-31T14:15:00+01:00","value":2.17},{"date":"2023-12-31T14:30:00+01:00","value":2.17},{"date":"2023-12-31T14:45:00+01:00","value":2.17},{"date":"2023-12-31T15:00:00+01:00","value":2.67},{"date":"2023-12-31T15:15:00+01:00","value":2.67},{"date":"2023-12-31T15:30:00+01:00","value":2.67},{"date":"2023-12-31T15:45:00+01:00","value":2.67},{"date":"2023-12-31T16:00:00+01:00","value":2.609},{"date":"2023-12-31T16:15:00+01:00","value":2.609},{"date":"2023-12-31T16:30:00+01:00","value":2.609},{"date":"2023-12-31T16:45:00+01:00","value":2.609},{"date":"2023-12-31T17:00:00+01:00","value":2.872},{"date":"2023-12-31T17:15:00+01:00","value":2.872},{"date":"2023-12-31T17:30:00+01:00","value":2.872},{"date":"2023-12-31T17:45:00+01:00","value":2.872},{"date":"2023-12-31T18:00:00+01:00","value":3.146},{"date":"2023-12-31T18:15:00+01:00","value":3.146},{"date":"2023-12-31T18:30:00+01:00","value":3.146},{"date":"2023-12-31T18:45:00+01:00","value":3.146},{"date":"2023-12-31T19:00:00+01:00","value":2.348},{"date":"2023-12-31T19:15:00+01:00","value":2.348},{"date":"2023-12-31T19:30:00+01:00","value":2.348},{"date":"2023-12-31T19:45:00+01:00","value":2.348},{"date":"2023-12-31T20:00:00+01:00","value":2.064},{"date":"2023-12-31T20:15:00+01:00","value":2.064},{"date":"2023-12-31T20:30:00+01:00","value":2.064},{"date":"2023-12-31T20:45:00+01:00","value":2.064},{"date":"2023-12-31T21:00:00+01:00","value":0.984},{"date":"2023-12-31T21:15:00+01:00","value":0.984},{"date":"2023-12-31T21:30:00+01:00","value":0.984},{"date":"2023-12-31T21:45:00+01:00","value":0.984},{"date":"2023-12-31T22:00:00+01:00","value":1.282},{"date":"2023-12-31T22:15:00+01:00","value":1.282},{"date":"2023-12-31T22:30:00+01:00","value":1.282},{"date":"2023-12-31T22:45:00+01:00","value":1.282},{"date":"2023-12-31T23:00:00+01:00","value":1.122},{"date":"2023-12-31T23:15:00+01:00","value":1.122},{"date":"2023-12-31T23:30:00+01:00","value":1.122},{"date":"2023-12-31T23:45:00+01:00","value":1.122}]}"`

And objects are looking like this:
![image](https://github.com/sirjojo69/ioBroker.awattar/assets/15886027/66431b33-109f-47e5-9f29-03c020835c1e)

So my question is: Is it possible to enhance your adapter for other epex spot provider as well ?

**Comment by sirjojo69** [comment]
hi,
sorry, this adapter is dsigned to just work with awattar api....
cheers
gereon
