### ISSUE TITLE
Start/Stop Grüner Punkt

### ISSUE THREAD

**Issue by detafun** [sirjojo69/ioBroker.awattar#3]
Ja der Grüne Punkt fehlt noch Aktiv oder Deaktiv
Also hier:
![grafik](https://user-images.githubusercontent.com/44980055/97629618-a260c200-1a2e-11eb-9fbb-9ea270879b74.png)

**Comment by sirjojo69** [comment]
den hat ein adapter mit mode "schedule" nicht.... er ist ja zu nichts connected (z.b. homematic oder FHEM oder so) ...
