### ISSUE TITLE
aWATTar Marketdata API - Nutzung von Start und End Parameter

### ISSUE THREAD

**Issue by awattarpeter** [sirjojo69/ioBroker.awattar#4]
Ruft man das aWATTar Marktdata API ohne Parameter auf (https://api.awattar.at/v1/marketdata) gibt diesen einem die nächsten 24 Stunden von jetzt aus. Ich würde empfehlen die Parameter start und end z.B immer mit (Heute Start des Tages und Morgen Ende des Tages) mitzugeben.

z.B:
https://api.awattar.de/v1/marketdata?start=1604016000000&end=1604188800000

Damit bekommt man für den nächsten Tag, wenn verfügbar immer die vollen Daten.

**Comment by awattarpeter** [comment]
Kleiner Nachtrag, wenn man manuelle Hilfe mit der Konvertierung von Zeitstempel in Epochmilliseconds braucht empfehle ich folgendes Tools: https://www.epochconverter.com/

**Comment by sirjojo69** [comment]
ist in 1.0.4 so umgesetzt.... Ich close das Issue mal hier. Sollte etwas nicht passen, bitte neues Issue aufmachen...
