### ISSUE TITLE
Keine Objekte

### ISSUE THREAD

**Issue by peterle-k** [sirjojo69/ioBroker.awattar#5]
Es werden nach Installation keine Objekte angelegt ...

**Comment by Habedere** [comment]
Waren bei mir auch erst einen Tag später drin.
Denke der muss die erstmal je nach Zeitfenster laden...

**Comment by sirjojo69** [comment]
der adapter muss erst ein - zweimal gelaufen sein. dafür kann man den schedule des adapters (kurzzeitig) z.b. auf * * * * * stellen, dann läuft er jede minute. Dann stellet man ihn wieder auf die Uhrzeit die man für richtig hält ...
