### ISSUE TITLE
Remove supportsCustom if no custom script is used - breaks Admin!!

### ISSUE THREAD

**Issue by Apollon77** [sirjojo69/ioBroker.awattar#7]
https://github.com/sirjojo69/ioBroker.awattar/blob/master/io-package.json#L55

If this is set also a custom_m.html needs to be in Admin folder. Please remove. this causes https://github.com/ioBroker/ioBroker.history/issues/84

**Comment by sirjojo69** [comment]
thx for the hint. will be fixed in next version....
