### ISSUE TITLE
Objekte um 0:00 Uhr aktualisieren

### ISSUE THREAD

**Issue by derLaas** [sirjojo69/ioBroker.awattar#8]
Hi,

danke für den Adapter, den ich wirklich sehr gern benutze!

Ich habe einen Verbesserungsvorschlag, der meiner Meinung nach den Umgang mit den Objekten vereinfachen würde.

Um 0:00 Uhr die Werte so im Objektbaum aktualisieren, dass die Stundenobjekte dem des aktuellen/neuen Tages entsprechen und dem entsprechend die Objekte > 25 wieder leeren ( da für diese noch keine Stundenpreise bekannt sind). Mit dem Update der neuen Preise (gegen 15 Uhr) können dann insb. diese Objekte > 25 aktualisiert werden (weil ja dann auch eine Information dazu vorliegt).

M.E.n. würde das den Umgang mit den Objekten deutlich vereinfachen.

Hinweis: Ich habe schon ausprobiert die Instanz um 0:15 Uhr einmal (zusätzlich) neu zustarten um vielleicht genau dieses Ergebnis zu erreichen, leider ohne Erfolg.

Über eine Rückmeldung zum Vorschlag würde ich mich sehr freuen.

beste Grüße
Lars

**Comment by sirjojo69** [comment]
Hi Lars,
sorry, bin wahrscheinlich zu doof, aber ich verstehe weder den sinn noch den Mehrwert. Egal wann der Adapter losläuft (du kannst das ja mit einem eigenen Schedule selber beeinflussen) holt er sich alle vorhandenen Werte bis übermorgen abend. D.h. du hast die werte für morgen (bzw. um 0.15 dann schon für heute) im objektbaum. den wert der stunde die dich interessiert kannst du dann über den tag und die uhrzeit aus dem objektbaum rausholen... ich versteh nicht ganz was dir da fehlt. Vielleicht meinst du "nur" eine neue Sortierung? Also der wert von 0 bis 1 uhr in awattar.0.prices.0 und so weiter. Falls für dich eine solche Sortierung Sinn macht (für welchen Use Case auch immer) kannst du dir das doch sehr einfach mit einem script dass um 0.15 läuft in eigene Datenpunkte "kopieren"...
VG
Gereon

**Comment by derLaas** [comment]
Hi Gereon,
Danke für deine schnelle Antwort!

die Objekte 0 bis 23 sollten m.E.n den aktuellen Tage abdecken.
24 bis 47 entsprechend dann Morgen und so weiter.

Jetzt habe ich soeben die Instanz nochmal gestartet und schon passten die Objekte.
Vielleicht habe ich auch was falsch gemacht, ich teste das die Tage noch einmal und melde mich, wenn ich eine Abweichung finde.

beste Grüße
Lars

**Comment by sirjojo69** [comment]
ah, ok. jetzt habe auch ich es verstanden ;-) 
Aber das können andere user anders sehen. Ich z.b. wäre für meine Anwendung der Daten aus diesem Adapter der Meinung das 22 und 23 auf jeden fall schon an diesem tag sein müssen, weil ich da schon anfangen würde meinen hausspeicher und meine elektro autos zu beladen.
Also ich denke, dass dir der Schedule des Adapters die Möglichkeit gibt das für dich so zu lösen wie du es für deinen Anwendungsfall brauchst. Von daher würde ich das Issue mal schliessen hier.
VG
Gereon
